### ISSUE TITLE
Error routing

### ISSUE THREAD

**Issue by njiipanji** [AnneAnnisa/rk#11]
Tidak bisa akses routing ke '/'

**Comment by fourirakbar** [comment]
Screenshoot errornya juga @njiipanji 
Karena ini bisa dibuka, mungkin ada yg salah config dikit.
![image](https://cloud.githubusercontent.com/assets/16026826/26272498/0bc48248-3d44-11e7-8926-4ee9eae5f27b.png)

**Comment by njiipanji** [comment]
![image](https://cloud.githubusercontent.com/assets/15218998/26286068/16e39c48-3e86-11e7-8850-4b56bf5b532b.png)
Ini, barusan sudah pull repo yg terbaru tetep tidak bisa dibuka @fourirakbar

**Comment by fourirakbar** [comment]
Buat file .env

APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=


itu nggak ke push, soalnya masuk ke gitignore

**Comment by njiipanji** [comment]
Bukan masalah .env, ini errornya :

RuntimeException in C:\xampp\htdocs\rk\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php line 43:
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by rarasanggita** [comment]
sama kayak panji juga. gak bisa hehehe

**Comment by rarasanggita** [comment]
sudah bisa

**Comment by desyrahmi** [comment]
Lain kali .env nya dipush aja direname jadi .example.env

**Comment by njiipanji** [comment]
Sudah bisa
