### ISSUE TITLE
Halaman Login

### ISSUE THREAD

**Issue by desyrahmi** [AnneAnnisa/rk#12]
![image](https://cloud.githubusercontent.com/assets/15167554/26315127/535bf256-3f3a-11e7-926c-efd315b5c677.png)
 
letak remember me nya gak pas

**Comment by rarasanggita** [comment]
Tombol daftar peserta di halaman login eror (salah redirect kayaknya), trus kata2nya rancu, kayak mau nampilin data peserta, padahal mau daftar sebagai peserta

**Comment by vaniamc** [comment]
@rarasanggita Sebenernya itu untuk mau daftar sebagai peserta. Sudah diganti kata-katanya. Tolong dicek. Terima kasih

**Comment by vaniamc** [comment]
@desyrahmi tampilannya sudah diperbaiki. Mohon dicek. terima kasih

**Comment by desyrahmi** [comment]
Ok gan
